### ISSUE TITLE
Mirage Path Not Found 404

### ISSUE THREAD

**Issue by rovo79** [emberjs/guides#1147]
Hello,

I've followed the Tutorial Guide very closely but I am running into an issue trying to complete the Ember Data section. https://guides.emberjs.com/v2.2.0/tutorial/ember-data/

Index is coming up blank. When I inspect in Chrome I'm receiving a 404 for the rentals path. 
`GET http://localhost:4200/rentals 404 (Not Found)     --- jquery.js: 9664`

Greatly appreciate any insights. Would love to complete this tutorial. 

Thank you.

Environment—
Ember      : 2.2.0
Ember Data : 2.2.1
jQuery     : 1.11.3

Also, I am receiving this error following the above 404:
```
Error while processing route: index Adapter operation failed Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26437:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:65986:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:67290:16)
    at hash.error (http://localhost:4200/assets/vendor.js:67370:33)
    at fire (http://localhost:4200/assets/vendor.js:3373:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:3485:7)
    at done (http://localhost:4200/assets/vendor.js:9541:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:9943:8)logError @ ember.debug.js:27431defaultActionHandlers.error @ ember.debug.js:27374triggerEvent @ ember.debug.js:27485trigger @ ember.debug.js:51925Transition.trigger @ ember.debug.js:51739(anonymous function) @ ember.debug.js:51559tryCatch @ ember.debug.js:52258invokeCallback @ ember.debug.js:52273publish @ ember.debug.js:52241publishRejection @ ember.debug.js:52176(anonymous function) @ ember.debug.js:30835Queue.invoke @ ember.debug.js:320Queue.flush @ ember.debug.js:384DeferredActionQueues.flush @ ember.debug.js:185Backburner.end @ ember.debug.js:563Backburner.run @ ember.debug.js:685run @ ember.debug.js:20105hash.error @ rest-adapter.js:761fire @ jquery.js:3148self.fireWith @ jquery.js:3260done @ jquery.js:9316callback @ jquery.js:9718
ember.debug.js:30877Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26437:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:65986:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:67290:16)
    at hash.error (http://localhost:4200/assets/vendor.js:67370:33)
    at fire (http://localhost:4200/assets/vendor.js:3373:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:3485:7)
    at done (http://localhost:4200/assets/vendor.js:9541:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:9943:8)onerrorDefault @ ember.debug.js:30877exports.default.trigger @ ember.debug.js:52928(anonymous function) @ ember.debug.js:54177Queue.invoke @ ember.debug.js:320Queue.flush @ ember.debug.js:384DeferredActionQueues.flush @ ember.debug.js:185Backburner.end @ ember.debug.js:563Backburner.run @ ember.debug.js:685run @ ember.debug.js:20105hash.error @ rest-adapter.js:761fire @ jquery.js:3148self.fireWith @ jquery.js:3260done @ jquery.js:9316callback @ jquery.js:9718
```

**Comment by rovo79** [comment]
After researching more, I'm guessing this is maybe somehow related to Ember CLI not producing a JSONAPIadaptor? I'm completely new to this, and not sure.

https://github.com/ember-cli/ember-cli/issues/4787

**Comment by acorncom** [comment]
@rovo79 That could be it or you may need to update your jQuery to 2.x (for Mirage).  Could we move this discussion to the Slack `#needhelp` channel or Stackoverflow though?  If it's a bug in the guides, we should fix it, but other folks have done the guides and haven't run into this issue, so it's more likely to be your local setup :-)

**Comment by rovo79** [comment]
Definitely. Thank you for the hint. I will try adjusting my jQuery. 

Do I need a Slack invite to get into ?
https://embercommunity.slack.com

**Comment by acorncom** [comment]
@rovo79 Yes, you can get it by visiting https://ember-community-slackin.herokuapp.com/ (referenced on the http://emberjs.com/community/ page, but it's a bit buried).  See you shortly! :-)

**Comment by rovo79** [comment]
Thank you!

**Comment by alejandropc** [comment]
I experienced the same issue while following the tutorial. 
>ember -v
version: 2.2.0-beta.6
node: 4.2.4
npm: 2.14.10
os: win32 x64

**Comment by acorncom** [comment]
@alejandropc The latest docs (not yet deployed) have an extra bit of info them, but you'll need to restart your ember-cli server.  Doing that should fix things for you.  If it doesn't, please ask on Slack or StackOverflow. Thanks!

**Comment by alejandropc** [comment]
It worked! just as you mention: Restarting the ember-cli web server

Thanks!

**Comment by ve3** [comment]
I have the same issue. restart the ember server don't fix anything.

I'm on this tutorial step and can't get /rentals
https://guides.emberjs.com/v2.7.0/tutorial/installing-addons/

> DEBUG: -------------------------------
> vendor.js (line 16864)
> 
> DEBUG: Ember      : 2.7.2
> 
> vendor.js (line 16864)
> DEBUG: Ember Data : 2.7.0
> vendor.js (line 16864)
> 
> DEBUG: jQuery     : 2.2.4
> 
> vendor.js (line 16864)
> DEBUG: -------------------------------
> vendor.js (line 16864)
> DEBUG: For more advanced debugging, install the Ember Inspector from https://addons.mozilla.org/en-US/firefox/addon/ember-inspector/
> vendor.js (line 16864)
> UnrecognizedURLError: /rentals

**Comment by locks** [comment]
@ve3 visit our Slack group for more help, thanks.
