### ISSUE TITLE
"Building for production" step fails

### ISSUE THREAD

**Issue by jzaefferer** [emberjs/guides#1497]
I followed the [Getting Started / Quick Start guide](https://guides.emberjs.com/v2.6.0/getting-started/quick-start/). The last section is about Building for production. Running the command `ember build --env production` fails with this output:

```
$ ember build --env production
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
ENOENT: no such file or directory, open '/Users/jzaefferer/dev/ember-quickstart/dist/assets/ember-quickstart-82ce2153342967d72a40604a429e6d57.js'
Error: ENOENT: no such file or directory, open '/Users/jzaefferer/dev/ember-quickstart/dist/assets/ember-quickstart-82ce2153342967d72a40604a429e6d57.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at TreeSync.<anonymous> (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/tree-sync/index.js:59:19)
    at Array.forEach (native)
    at TreeSync.sync (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/tree-sync/index.js:50:14)
    at Class.module.exports.Task.extend.copyToOutputPath (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:124:10)
    at /Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:132:21
    at lib$rsvp$$internal$$tryCatch (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
```
Being new to Ember, that's a rather cryptic/useless error. I can't even tell what it was trying to do when it failed.

Since this happened while following the quick start guide, I figured I'd report it here. I don't know where else I'd report this anyway.

May help:
```
$ ember --version
ember-cli: 2.5.1
node: 5.3.0
os: darwin x64
```

Otherwise the quick start guide is working well. I really like the diff view to show what code to add and remove!

**Comment by jzaefferer** [comment]
Not sure if this is going to help... I tried again (while installing watchman elsewhere, so that warning disappeared, and it worked:

```
$ ember build --env production
Built project successfully. Stored in "dist/".
File sizes:
 - ember-quickstart-82ce2153342967d72a40604a429e6d57.js: 9.4 KB (1.99 KB gzipped)
 - ember-quickstart-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - vendor-679364b4c6a3067afe9c0adfd7714511.js: 691.06 KB (180.22 KB gzipped)
 - vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```
I then wanted to go back to running the dev server... which failed:
```
$ ember server
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT: no such file or directory, open '/Users/jzaefferer/dev/ember-quickstart/dist/assets/ember-quickstart.css'
Error: ENOENT: no such file or directory, open '/Users/jzaefferer/dev/ember-quickstart/dist/assets/ember-quickstart.css'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at TreeSync.<anonymous> (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/tree-sync/index.js:59:19)
    at Array.forEach (native)
    at TreeSync.sync (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/tree-sync/index.js:50:14)
    at Class.module.exports.Task.extend.copyToOutputPath (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:124:10)
    at /Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:132:21
    at lib$rsvp$$internal$$tryCatch (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jzaefferer/dev/ember-quickstart/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, rmdir '/Users/jzaefferer/dev/ember-quickstart/dist/assets'
    at Error (native)
```
Trying that again, and it... worked!

Not sure what's going on there. Let me know if there's other info I can share to help track this down.

**Comment by locks** [comment]
This is sounding like a bad npm install, or somesuch. Hm, not sure we can do anything about it.

**Comment by acorncom** [comment]
@jzaefferer I'll close this for now, but if you end up having a steady way of reproducing this issue, please let us know!
