### ISSUE TITLE
`ember new` requires git, but the quick start guide doesn’t mention this

### ISSUE THREAD

**Issue by chris-morgan** [emberjs/guides#1579]
```
C:\Users\me>ember new draw
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app\app.js
  create app\components\.gitkeep
  create app\controllers\.gitkeep
  create app\helpers\.gitkeep
  create app\index.html
  create app\models\.gitkeep
  create app\resolver.js
  create app\router.js
  create app\routes\.gitkeep
  create app\styles\app.css
  create app\templates\components\.gitkeep
  create bower.json
  create config\environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public\crossdomain.xml
  create public\robots.txt
  create testem.js
  create tests\.jshintrc
  create tests\helpers\destroy-app.js
  create tests\helpers\module-for-acceptance.js
  create tests\helpers\resolver.js
  create tests\helpers\start-app.js
  create tests\index.html
  create tests\integration\.gitkeep
  create tests\test-helper.js
  create tests\unit\.gitkeep
  create vendor\.gitkeep
Installed packages for tooling via npm.
Error creating new application. Removing generated directory `./draw`
git is not installed or not in the PATH
Error: git is not installed or not in the PATH
    at createError (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\util\createError.js:4:15)
    at GitHubResolver.GitResolver (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\core\resolvers\GitResolver.js:35:15)
    at GitHubResolver.GitRemoteResolver (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\core\resolvers\GitRemoteResolver.js:10:17)
    at new GitHubResolver (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\core\resolvers\GitHubResolver.js:13:23)
    at C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\core\resolverFactory.js:18:16
    at C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:1229:26
    at _fulfilled (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:796:13)
    at C:\Users\me\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\node_modules\q\q.js:556:49
```

[No one](https://guides.emberjs.com/v2.7.0/getting-started/quick-start/) told *me* I had to have Git installed.

(I use WSL and have Git installed on the Ubuntu side, but on the Windows side I hadn’t gotten around to installing Git yet.)

**Comment by locks** [comment]
The [Installing Ember](https://guides.emberjs.com/v2.7.0/getting-started/#toc_git) does, though it comes after. Going to suggest something, one sec.

**Comment by locks** [comment]
@chris-morgan do you think https://github.com/emberjs/guides/pull/1581/files#diff-41d19b956479ca7b821c55def80da82b would be sufficient?
You are sort of an edge case, since most users seem to have git installed, so thank you for bringing this to our attention. I will also investigate the possibility of making git a soft requirement.

**Comment by chris-morgan** [comment]
@locks: Well, the NPM requirement is already written out and Git is the only other actual *requirement*. (Bower gets installed into node_modules). It’d be kinda nice to mention Git explicitly. But yeah, it’s fine.

**Comment by locks** [comment]
I'm following up with the Ember CLI on the question of making Git a soft dependency, thanks for your feedback.

**Comment by rwjblue** [comment]
It should not be required. We used to detect git was missing and just carry on nicely, if we now blow up when there is no fit global then that is a regression.
