### ISSUE TITLE
[dev] bundle exec middleman fails

### ISSUE THREAD

**Issue by locks** [emberjs/guides#1954]
Stack:

```
$ bundle exec middleman
bundler: failed to load command: middleman (/usr/local/bin/middleman)
LoadError: Could not open library 'c': dlopen(c, 5): image not found.
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
  /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib'
  /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
  /Library/Ruby/Gems/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.0/lib/ethon/libc.rb:8:in `<module:Libc>'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.0/lib/ethon/libc.rb:6:in `<module:Ethon>'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.0/lib/ethon/libc.rb:1:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.0/lib/ethon.rb:10:in `require'
  /Library/Ruby/Gems/2.0.0/gems/ethon-0.8.0/lib/ethon.rb:10:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.8.0/lib/typhoeus.rb:2:in `require'
  /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.8.0/lib/typhoeus.rb:2:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer/url_validator.rb:1:in `require'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer/url_validator.rb:1:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer.rb:4:in `require'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer.rb:4:in `block in require_all'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer.rb:3:in `each'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer.rb:3:in `require_all'
  /Library/Ruby/Gems/2.0.0/gems/html-proofer-2.5.2/lib/html/proofer.rb:8:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:105:in `require'
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:105:in `rescue in block in require'
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:82:in `block in require'
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
  /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
  /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
  /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/bin/middleman:10:in `<top (required)>'
  /usr/local/bin/middleman:23:in `load'
  /usr/local/bin/middleman:23:in `<top (required)>'
```

**Comment by acorncom** [comment]
Does this happen if you are using Ruby 2.2+?

**Comment by locks** [comment]
Hm, good question. I think I even filed this on behalf of someone.
Let's reopen if someone runs into it.
