### ISSUE TITLE
New tutorial environment acceptance test fail

### ISSUE THREAD

**Issue by robwelan** [emberjs/guides#2102]
I am on this page:
https://guides.emberjs.com/v2.16.0/tutorial/acceptance-test/

I get to this instruction and run it:
Now run your test suite with the CLI command, ember test --server.

And instead of getting passed tests, I get this, plus

Error:

Source: | at Module.callback (http://localhost:7357/assets/tests.js:8:19)     at Module.exports (http://localhost:7357/assets/vendor.js:111:32)     at requireModule (http://localhost:7357/assets/vendor.js:32:18)     at TestLoader.<anonymous> (http://localhost:7357/assets/test-support.js:8105:11)     at TestLoader.require (http://localhost:7357/assets/test-support.js:8095:27)     at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:8087:16)     at loadTests (http://localhost:7357/assets/test-support.js:7932:22)
-- | --

and
ESLint | tests: should show details for a selected rental (1, 0, 1)Rerun1 ms
Source: at Object. (http://localhost:7357/assets/tests.js:19:21) at runTest (http://localhost:7357/assets/test-support.js:4056:30) at Test.run (http://localhost:7357/assets/test-support.js:4042:6) at http://localhost:7357/assets/test-support.js:4248:12 at Object.advance (http://localhost:7357/assets/test-support.js:3694:26) at begin (http://localhost:7357/assets/test-support.js:5515:20) at http://localhost:7357/assets/test-support.js:5475:6
ESLint | tests: visiting / (1, 0, 1)Rerun1 ms
Source: at Object. (http://localhost:7357/assets/tests.js:21:21) at runTest (http://localhost:7357/assets/test-support.js:4056:30) at Test.run (http://localhost:7357/assets/test-support.js:4042:6) at http://localhost:7357/assets/test-support.js:4248:12 at Object.advance (http://localhost:7357/assets/test-support.js:3694:26) at begin (http://localhost:7357/assets/test-support.js:5515:20) at http://localhost:7357/assets/test-support.js:5475:6

I don't know where to start on how to fix this.

**Comment by robwelan** [comment]
Sorry: error was between chair and keyboard. I misread the instructions in the '/tests/acceptance/list-rentals-test.js' box, and I neglected to remove '{{welcome-page}}' on an earlier page.
